
DROP TABLE IF EXISTS "clusters";
CREATE TABLE "clusters" (
	"id" BIGINT,
	"creator_id" BIGINT, -- References "users"
	"name" VARCHAR(256),
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"visibility" ENUM('public', 'unlisted'),

	CONSTRAINT "fk_cluster__creator_id"
		FOREIGN KEY ("creator_id")
			REFERENCES "users"("id")
				ON DELETE CASCADE,

	PRIMARY KEY ("id")
);